# Generated by Django 5.1.6 on 2025-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_currencyrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
