# Generated by Django 5.1.6 on 2025-03-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0004_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
