# Generated by Django 5.1.6 on 2025-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0005_alter_warehouse_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=25),
        ),
    ]
