# Generated by Django 5.1.6 on 2025-03-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0007_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterials",
            name="version",
            field=models.CharField(default="1.0", max_length=30),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="unit_of_measure",
            field=models.CharField(default="units", max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("ISSUED", "Issued"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ISSUED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SCHEDULED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("SEMI_ANNUAL", "Semi-Annual"),
                    ("ANNUAL", "Annual"),
                    ("USAGE_BASED", "Based on Usage"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingorder",
            name="bom_version",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturingorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLANNED", "Planned"),
                    ("MATERIAL_PENDING", "Materials Pending"),
                    ("READY", "Ready to Start"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ON_HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Paid"),
                ],
                default="UNPAID",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("ORDERED", "Ordered"),
                    ("PARTIAL", "Partially Received"),
                    ("RECEIVED", "Received"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="qualitycheck",
            name="result",
            field=models.CharField(
                choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("WARNING", "Warning")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready for Shipment"),
                    ("PARTIAL", "Partially Shipped"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning (6AM-2PM)"),
                    ("AFTERNOON", "Afternoon (2PM-10PM)"),
                    ("NIGHT", "Night (10PM-6AM)"),
                    ("CUSTOM", "Custom Hours"),
                ],
                default="MORNING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ABSENT", "Absent"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SCHEDULED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workstation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPERATIONAL", "Operational"),
                    ("MAINTENANCE", "Under Maintenance"),
                    ("BREAKDOWN", "Breakdown"),
                    ("INACTIVE", "Inactive"),
                ],
                default="OPERATIONAL",
                max_length=30,
            ),
        ),
    ]
