# Generated by Django 5.1.6 on 2025-03-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_alter_billofmaterials_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.IntegerField(default=5000)),
            ],
        ),
        migrations.AlterField(
            model_name="shift",
            name="workstation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="erp.workstation",
            ),
        ),
    ]
