# Generated by Django 5.1.6 on 2025-03-07 00:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_ordernumber_alter_shift_workstation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "Invoice", "verbose_name_plural": "Invoices"},
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_nip",
            field=models.CharField(
                max_length=15, null=True, verbose_name="NIP (Tax ID)"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gross_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CREDIT_CARD", "Credit Card"),
                    ("CASH", "Cash"),
                    ("PAYPAL", "PayPal"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issued_date",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sales_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="erp.salesorder",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("ISSUED", "Issued"),
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partially Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ISSUED",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
