# Generated by Django 5.1.6 on 2025-03-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_alter_invoice_options_invoice_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="generated_pdf",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
