# Generated by Django 5.1.6 on 2025-03-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0011_invoice_generated_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="company_phone",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer_phone",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
